# Generated by Django 4.2.5 on 2023-09-29 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='max_quota',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coruse_id', to='Register.student'),
        ),
    ]
