# Generated by Django 4.2.5 on 2023-09-29 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0003_subject_is_open_subject_max_quota_alter_subject_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
        migrations.AddField(
            model_name='subject',
            name='students',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Register.student'),
            preserve_default=False,
        ),
    ]
