# Generated by Django 4.2.5 on 2023-10-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0006_alter_subject_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='quota',
            field=models.IntegerField(default=0),
        ),
    ]
