# Generated by Django 4.2.5 on 2023-10-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0007_subject_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='id_course',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
