# Generated by Django 4.2.5 on 2023-10-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0008_subject_id_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='quota',
            field=models.IntegerField(default=50),
        ),
    ]
